cmake_minimum_required(VERSION 3.22.1)
project(strangerpro)
find_package(oboe REQUIRED CONFIG)
add_library(strangerpro SHARED native-lib.cpp fm_engine.cpp dexed_wrapper.cpp surge_wrapper.cpp)
target_include_directories(strangerpro PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(strangerpro oboe::oboe android log OpenSLES)
target_compile_options(strangerpro PRIVATE -O3 -ffast-math -Wall -Wno-unused-variable)
set_property(TARGET strangerpro PROPERTY CXX_STANDARD 17)
